services:
  sonnetdb:
    build:
      context: SonnetDB
      dockerfile: src/SonnetDB/Dockerfile

  pg_iotsharp:
    build:
      context: .
      dockerfile: IoTSharp/Dockerfile
      args:
        SOURCE_ROOT: .

  sonnetdb_iotsharp:
    build:
      context: .
      dockerfile: IoTSharp/Dockerfile
      args:
        SOURCE_ROOT: .
