services:
  pg_iotsharp:
    build:
      context: ..
      dockerfile: IoTSharp/IoTSharp/Dockerfile
      args:
        SOURCE_ROOT: IoTSharp

  sonnetdb_iotsharp:
    build:
      context: ..
      dockerfile: IoTSharp/IoTSharp/Dockerfile
      args:
        SOURCE_ROOT: IoTSharp
