export const signUpRule: any[] = [
	{
		type: 'input',
		field: 'email',
		title: '登录邮箱',
		info: '',
		props: {
			type: 'text',
			placeholder: '请输入登录邮箱',
			showPassword: false,
		},
		_fc_drag_tag: 'input',
		hidden: false,
		display: true,
		validate: [
			{
				trigger: 'change',
				message: '请输入正确的邮箱地址',
				pattern: /^[a-z0-9]+([._\\-]*[a-z0-9])*@([a-z0-9]+[-a-z0-9]*[a-z0-9]+\.){1,63}[a-z0-9]+$/,
				type: 'email',
				required: true,
			},
		],
	},
	{
		type: 'input',
		field: 'customerName',
		title: '管理员名称',
		info: '',
		props: {
			type: 'text',
			placeholder: '请输入管理员名称',
		},
		_fc_drag_tag: 'input',
		hidden: false,
		display: true,
		$required: '请输入管理员名称',
	},
	{
		type: 'input',
		field: 'password',
		title: '密码',
		info: '',
		props: {
			type: 'password',
			placeholder: '请输入密码',
			showPassword: true,
		},
		_fc_drag_tag: 'input',
		hidden: false,
		display: true,
		$required: '请输入密码',
	},
	{
		type: 'input',
		field: 'passwordCheck',
		title: '确认密码',
		info: '',
		props: {
			type: 'password',
			placeholder: '请再次输入密码',
			showPassword: true,
		},
		_fc_drag_tag: 'input',
		hidden: false,
		display: true,
		value: '',
		validate: [],
	},
	{
		type: 'input',
		field: 'tenantName',
		title: '租户名称',
		info: '',
		props: {
			placeholder: '请输入租户名称',
			showPassword: false,
			type: 'text',
		},
		_fc_drag_tag: 'input',
		hidden: false,
		display: true,
		value: '',
		validate: [
			{
				required: true,
				message: '请输入租户名称',
			},
		],
	},
	{
		type: 'input',
		field: 'tenantEMail',
		title: '租户邮箱',
		info: '',
		props: {
			placeholder: '请输入租户邮箱',
			showPassword: false,
			type: 'text',
		},
		_fc_drag_tag: 'input',
		hidden: false,
		display: true,
		value: '',
		validate: [
			{
				trigger: 'change',
				message: '请输入正确的租户邮箱地址',
				pattern: /^[a-z0-9]+([._\\-]*[a-z0-9])*@([a-z0-9]+[-a-z0-9]*[a-z0-9]+\.){1,63}[a-z0-9]+$/,
				type: 'email',
				required: true,
			},
		],
	},
	{
		type: 'input',
		field: 'customerEMail',
		title: '联系邮箱',
		info: '',
		props: {
			placeholder: '请输入联系邮箱',
			showPassword: false,
			type: 'text',
		},
		_fc_drag_tag: 'input',
		hidden: false,
		display: true,
		value: '',
		validate: [
			{
				trigger: 'change',
				message: '请输入正确的联系邮箱地址',
				pattern: /^[a-z0-9]+([._\\-]*[a-z0-9])*@([a-z0-9]+[-a-z0-9]*[a-z0-9]+\.){1,63}[a-z0-9]+$/,
				type: 'email',
				required: true,
			},
		],
	},
	{
		type: 'input',
		field: 'phoneNumber',
		title: '联系电话',
		info: '',
		props: {
			placeholder: '请输入联系电话',
			showPassword: false,
			type: 'text',
		},
		_fc_drag_tag: 'input',
		hidden: false,
		display: true,
		value: '',
		validate: [
			{
				required: true,
				trigger: 'blur',
				message: '请输入正确的手机号',
				pattern: /^(1[3456789]\d{9})$/,
			},
		],
	},
];
