name: Deploy to GitHub Pages

on:
  push:
    branches: [master]
    paths: [docs/**]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
          cache: yarn
      - name: Build website
        working-directory: docs
        run: |
          yarn  install --frozen-lockfile 
          yarn  build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: docs/build
      - name: syncfile
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
         server: wh-nb3if1wq7i6udh1xtsb.my3w.com
         username: ${{ secrets.FTPUSERNAME }}
         password: ${{ secrets.FTPPASSWORD }}
         local-dir:  docs/build/
         server-dir: htdocs/
