name: .NET Core build

on:
  push:
    branches: [ master ]
    paths: [IoTSharp.*/**,IoTSharp/**]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: InferSharp
      uses: microsoft/infersharpaction@v0.2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: 8.0.x 
    - name: Build
      run: dotnet build  ./IoTSharp.sln  --configuration Release 
    - name: Test
      run: dotnet test  ./IoTSharp.sln --configuration Release  --no-build --verbosity normal


      
      
